services:
  - type: web
    name: saint-andrews-market
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: rewrite
        source: /contact
        destination: /index.html
      - type: rewrite
        source: /gallery
        destination: /index.html
      - type: rewrite
        source: /home
        destination: /index.html 